# Contenu final et correct pour docker-compose.yaml
services:
  ansible:
    hostname: ansible
    build:
      context: .
      dockerfile: ./ansible-node/Dockerfile
    container_name: ansible
    ports:
      - "2222:22"
    volumes:
      - ./projet:/root/projet
    networks:
      - ansible_net

  client1:
    hostname: client1
    build:
      context: .
      dockerfile: ./ubuntu-ssh/Dockerfile
    container_name: client1
    ports:
      - "2223:22"
    networks:
      - ansible_net

  client2:
    hostname: client2
    build:
      context: .
      dockerfile: ./ubuntu-ssh/Dockerfile
    container_name: client2
    ports:
      - "2224:22"
    networks:
      - ansible_net

  client3:
    hostname: client3
    build:
      context: .
      dockerfile: ./rocky-ssh/Dockerfile
    container_name: client3
    ports:
      - "2225:22"
    networks:
      - ansible_net

  client4:
    hostname: client4
    build:
      context: .
      dockerfile: ./rocky-ssh/Dockerfile
    container_name: client4
    ports:
      - "2226:22"
    networks:
      - ansible_net

  quiz-ansible:
    image: ftutorials/quiz:ansible-1
    container_name: quiz-ansible
    ports:
      - "3000:3000"
    networks:
      - ansible_net

networks:
  ansible_net:
    driver: bridge
