---
- name: Copier un fichier vers les clients
  hosts: all
  gather_facts: false

  tasks:
    - name: Copier le fichier sdv.conf vers /tmp
      ansible.builtin.copy:
        src: /root/sdv.conf
        dest: /tmp/sdv.conf
